CREATE TABLE `param_metrics2` (
  `id` int(11) NOT NULL,
  `status` int(11) NOT NULL DEFAULT '0',
  `ret_age` int(11) NOT NULL,
  `ret_length` int(11) NOT NULL COMMENT '				',
  `ret_sex` varchar(2) NOT NULL,
  `param_equitypct` double NOT NULL,
  `param_sfactor` double NOT NULL,
  `param_smoother` double NOT NULL,
  `param_attenuator` double NOT NULL,
  `param_sconstant` double NOT NULL,
  `initspend` double DEFAULT NULL,
  `worst_shortfall` double DEFAULT NULL,
  `lifespend` double DEFAULT NULL,
  `ce1` double DEFAULT NULL,
  `ce2` double DEFAULT NULL,
  `ce4` double DEFAULT NULL,
  `probmaxdecline0` double DEFAULT NULL,
  `probmaxdecline10` double DEFAULT NULL,
  `probmaxdecline20` double DEFAULT NULL,
  `probmaxdecline30` double DEFAULT NULL,
  `probmaxdecline40` double DEFAULT NULL,
  `probmaxdecline50` double DEFAULT NULL,
  `spend_std` double DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ix_unique` (`param_equitypct`,`param_sfactor`,`param_smoother`,`param_attenuator`,`param_sconstant`,`ret_age`,`ret_length`,`ret_sex`),
  KEY `ix_param_equitypct` (`param_equitypct`),
  KEY `ix_param_sfactor` (`param_sfactor`),
  KEY `ix_param_smoother` (`param_smoother`),
  KEY `ix_param_attenuator` (`param_attenuator`),
  KEY `ix_param_sconstant` (`param_sconstant`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1
